#!/usr/bin/env node
/**
 * parse_notes.js — Parse Apple Notes plaintext (from clipboard) into structured data.js
 * Input format: plaintext with "- [x]" (checked) and "- [ ]" (unchecked) checklist markers
 * Reads stdin with two sections: ===BJ_NOTE=== and ===TRAVEL_NOTE===
 * Writes data.js to the path given as argv[1]
 */

const fs = require('fs');
const path = require('path');

const outPath = process.argv[2];
if (!outPath) { console.error('Usage: node parse_notes.js <output_path>'); process.exit(1); }

let input = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', chunk => input += chunk);
process.stdin.on('end', () => {
  const parts = input.split(/===TRAVEL_NOTE===/);
  const bjRaw = (parts[0] || '').replace(/===BJ_NOTE===/, '');
  const travelRaw = parts[1] || '';

  const bjItems = parseBJNote(bjRaw);
  const travelItems = parseTravelNote(travelRaw);

  // Deduplicate by normalized name+region (keep richer entry)
  function normName(s){ return s.replace(/[\s·\-—/：:，,。、（）()《》]+/g,'').toLowerCase(); }
  const raw = [...bjItems, ...travelItems];
  const allItems = [];
  const seenNorms = []; // [{norm, idx}]
  for (const d of raw) {
    const norm = normName(d.name) + '|' + d.region;
    // Check exact match
    let dupIdx = seenNorms.findIndex(s => s.norm === norm);
    // Check substring match (e.g. "面之游" vs "面之游·拉面", "金海湖" vs "平谷金海湖景区")
    // Chinese names: min 3 chars (=3 hanzi). English names: min 6 chars to avoid "cafe" etc.
    if (dupIdx === -1) {
      const nameNorm = normName(d.name);
      const hasCJK = /[\u4e00-\u9fff]/.test(d.name);
      const minLen = hasCJK ? 3 : 5;
      if (nameNorm.length >= minLen) {
        dupIdx = seenNorms.findIndex(s => {
          const sName = s.norm.split('|')[0];
          const sRegion = s.norm.split('|')[1];
          if (sRegion !== d.region) return false;
          const shorter = sName.length < nameNorm.length ? sName : nameNorm;
          const longer = sName.length < nameNorm.length ? nameNorm : sName;
          const sHasCJK = /[\u4e00-\u9fff]/.test(shorter);
          const sMinLen = sHasCJK ? 3 : 5;
          return shorter.length >= sMinLen && longer.includes(shorter);
        });
      }
    }
    if (dupIdx === -1) {
      seenNorms.push({ norm, idx: allItems.length });
      allItems.push(d);
    } else {
      // Merge: keep the entry with more info, combine descs
      const existing = allItems[seenNorms[dupIdx].idx];
      // Prefer visited entry
      if (d.visited && !existing.visited) existing.visited = true;
      if (d.star && !existing.star) existing.star = true;
      // Keep shorter name (usually cleaner)
      if (d.name.length < existing.name.length) existing.name = d.name;
      // Merge nameEn
      if (d.nameEn && !existing.nameEn) existing.nameEn = d.nameEn;
      // Merge desc (append unique info)
      if (d.desc && d.desc !== existing.desc) {
        existing.desc = existing.desc ? existing.desc + ' ' + d.desc : d.desc;
      }
      // Keep more specific area
      if (d.area !== '其他' && existing.area === '其他') existing.area = d.area;
    }
  }

  const js = `// Auto-generated by sync.sh at ${new Date().toISOString()}\n// Do NOT edit manually — your changes will be overwritten.\nconst DATA = ${JSON.stringify(allItems, null, 2)};\n`;
  fs.writeFileSync(outPath, js, 'utf8');
  const visitedCount = allItems.filter(d => d.visited).length;
  console.log(`[parse] Wrote ${allItems.length} items (${visitedCount} visited) to ${path.basename(outPath)}`);
});

// ── Helpers ──

/**
 * Extract checklist items from plaintext.
 * Lines starting with "- [x]" are visited, "- [ ]" are not.
 * Lines without checkbox prefix are also included (not visited).
 */
function extractChecklistLines(text) {
  const results = [];
  for (const raw of text.split('\n')) {
    const line = raw.trim();
    if (!line || line.length < 3) continue;

    const checkedMatch = line.match(/^- \[x\]\s*(.+)/i);
    const uncheckedMatch = line.match(/^- \[ \]\s*(.+)/);

    if (checkedMatch) {
      results.push({ text: checkedMatch[1].trim(), visited: true });
    } else if (uncheckedMatch) {
      results.push({ text: uncheckedMatch[1].trim(), visited: false });
    }
    // Skip non-checklist lines (headers, blanks, etc.)
  }
  return results;
}

// ── Beijing note parser ──

function parseBJNote(text) {
  // Split into 吃 and 玩 sections
  const eatSplit = text.split(/北京-吃/i);
  const playSplit = text.split(/北京-玩/i);

  let eatText = '';
  let playText = '';

  if (eatSplit.length > 1 && playSplit.length > 1) {
    const afterEat = eatSplit.slice(1).join('');
    const playIdx = afterEat.search(/北京-玩/i);
    if (playIdx > -1) {
      eatText = afterEat.substring(0, playIdx);
      playText = afterEat.substring(playIdx);
    } else {
      eatText = afterEat;
      playText = playSplit.slice(1).join('');
    }
  } else if (eatSplit.length > 1) {
    eatText = eatSplit.slice(1).join('');
  } else {
    eatText = text;
  }

  const eatLines = extractChecklistLines(eatText);
  const playLines = extractChecklistLines(playText);

  const results = [];

  for (const { text: line, visited } of eatLines) {
    const item = parseBJEatLine(line);
    if (visited) item.visited = true;
    results.push(item);
  }
  for (const { text: line, visited } of playLines) {
    const item = parseBJPlayLine(line);
    if (visited) item.visited = true;
    results.push(item);
  }

  return results;
}

function parseBJEatLine(raw) {
  const star = raw.includes('🌟');
  const visited = raw.includes('✅');
  const line = raw.replace(/🌟/g, '').replace(/✅/g, '').trim();

  const cat = guessEatCategory(line);
  const { name, nameEn, desc, tags } = parseNameAndDesc(line);
  // Try area from full line first, then from desc
  const area = guessBeijingArea(line) !== '其他' ? guessBeijingArea(line) : guessBeijingArea(desc);

  return { name, nameEn, cat, region: '北京', area, desc, star, visited, tags };
}

function parseBJPlayLine(raw) {
  const star = raw.includes('🌟');
  const visited = raw.includes('✅');
  const line = raw.replace(/🌟/g, '').replace(/✅/g, '').trim();

  const cat = guessPlayCategory(line);
  const area = guessBeijingArea(line);
  const { name, nameEn, desc, tags } = parseNameAndDesc(line);

  return { name, nameEn, cat, region: '北京', area, desc, star, visited, tags };
}

function parseNameAndDesc(line) {
  let name = line;
  let nameEn = '';
  let desc = '';
  let tags = [];

  // 1. Strip "category：" prefix (e.g. "日料：藏善日本料理", "风景：东灵山")
  //    Also strip "live music:" prefix and "酒吧：" prefix
  const catPrefixMatch = name.match(/^(甜点|日料|意大利|湖南菜|火锅|咖啡|酒吧|面包|风景|公园|艺术园区|摩洛哥菜|live music)[：:]\s*(.+)$/i);
  if (catPrefixMatch) {
    name = catPrefixMatch[2].trim();
  }

  // 1b. Strip area/province/country prefix (e.g. "密云：日光山谷" → "日光山谷")
  const areaPrefixMatch = name.match(/^(密云|顺义|延庆|门头沟|怀柔|平谷|丰台|海淀|昌平|房山|通州|大兴|石景山|山西|山东|云南|浙江|贵州|福建|广西|湖南|江西|四川|新疆|西藏|河北|河南|甘肃|安徽|福州|厦门|泉州|桂林|大理|法国|德国|瑞士|意大利|希腊|韩国|摩洛哥|马来西亚|塞尔维亚|格鲁吉亚|以色列|奥地利|匈牙利)[：:]\s*(.+)$/);
  if (areaPrefixMatch && areaPrefixMatch[2].trim().length >= 2) {
    name = areaPrefixMatch[2].trim();
  }

  // 1c. Strip 《》book/show prefix (e.g. "极限挑战》恩阳古镇" → "恩阳古镇")
  const angleBracket = name.match(/^《?[^》]+》(.+)$/);
  if (angleBracket && angleBracket[1].trim().length >= 2) {
    name = angleBracket[1].trim();
  }

  // 2. Strip "北京市 · " prefix
  name = name.replace(/^北京市\s*·\s*/, '');

  // 3. Extract parenthetical content as desc — handle BOTH closed and unclosed parens
  const closedParen = name.match(/^([^（(]+)[（(](.+?)[）)](.*)$/);
  const openParen = name.match(/^([^（(]+)[（(](.+)$/);

  if (closedParen) {
    name = closedParen[1].trim();
    desc = closedParen[2].trim();
    const rest = closedParen[3].trim();
    if (rest) desc += ' ' + rest;
  } else if (openParen && openParen[1].trim().length >= 2) {
    // Unclosed paren — everything after ( is desc
    name = openParen[1].trim();
    desc = openParen[2].replace(/[）)]+$/, '').trim();
  }

  // 4. If name has both Chinese and English, try to split
  const mixMatch = name.match(/^(.+?)\s+([A-Za-z][\w\s&'".·-]+)$/);
  const mixMatch2 = name.match(/^([A-Za-z][\w\s&'".·-]+)\s+(.+)$/);
  if (mixMatch && /[\u4e00-\u9fff]/.test(mixMatch[1])) {
    name = mixMatch[1].trim();
    nameEn = mixMatch[2].trim();
  } else if (mixMatch2 && /[\u4e00-\u9fff]/.test(mixMatch2[2])) {
    nameEn = mixMatch2[1].trim();
    name = mixMatch2[2].trim();
  }

  // 4b. If nameEn looks like the real name and name looks like address, swap them
  if (nameEn && /(\d+号|大街|小街|北街|南街|路\d|街\d|胡同\d)/.test(name) && !/(\d+号|街|路)/.test(nameEn)) {
    const tmp = name;
    name = nameEn;
    desc = desc ? tmp + ' ' + desc : tmp;
    nameEn = '';
  }
  // 4c. If name starts with full address pattern (北京/东城/区+路+号), extract actual name
  if (!nameEn && /^(北京|东城|西城|朝阳|海淀|丰台|石景山|通州|昌平|大兴|房山|门头沟|顺义|密云|怀柔|平谷|延庆)/.test(name) && /\d+号/.test(name)) {
    const addrNameSplit = name.match(/^(.+?\d+号[^\s]*)\s+(.+)$/);
    if (addrNameSplit && addrNameSplit[2].trim().length >= 2) {
      desc = desc ? addrNameSplit[1].trim() + ' ' + desc : addrNameSplit[1].trim();
      name = addrNameSplit[2].trim();
    }
  }

  // 5. Clean up name — remove trailing punctuation, URLs, "to" chains
  name = name.replace(/https?:\/\/\S+/g, '').trim();  // strip URLs
  name = name.replace(/[：:，,]+$/, '').trim();
  name = name.replace(/to$/, '').trim();
  // Split "AtoB toC" chains — keep first segment as name, rest as desc (route)
  if (/to[\u4e00-\u9fff]/.test(name) && (name.match(/to/g)||[]).length >= 2) {
    const toParts = name.split(/to/);
    name = toParts[0].trim();
    const route = toParts.slice(1).map(s=>s.trim()).filter(Boolean).join(' → ');
    desc = desc ? route + ' ' + desc : route;
  }
  // If name still has "address：" pattern, split it
  const addrSplit = name.match(/^(.+?)[：:](.+?[街路号].*)$/);
  if (addrSplit && addrSplit[1].length >= 2) {
    desc = desc ? addrSplit[2].trim() + ' ' + desc : addrSplit[2].trim();
    name = addrSplit[1].trim();
  }
  // General colon split: "Name：location/feature" (e.g. "MAO： 五棵松")
  if (name.length > 4 && /[：:]/.test(name)) {
    const colonSplit = name.match(/^(.{2,}?)[：:]\s*(.+)$/);
    if (colonSplit && colonSplit[1].trim().length >= 2 && colonSplit[2].trim().length >= 1) {
      desc = desc ? colonSplit[2].trim() + ' ' + desc : colonSplit[2].trim();
      name = colonSplit[1].trim();
    }
  }
  // Location-dash-name pattern: "大栅栏-berrybeans" → name=berrybeans, desc=大栅栏
  if (name.length > 4) {
    const locDash = name.match(/^([\u4e00-\u9fff]{2,4})[-\-]([A-Za-z].+)$/);
    if (locDash) {
      desc = desc ? locDash[1].trim() + ' ' + desc : locDash[1].trim();
      name = locDash[2].trim();
    }
  }
  // For names > 6 chars: split at comma/，to separate name from features
  if (name.length > 6) {
    const commaSplit = name.match(/^(.{2,}?)[，,]\s*(.+)$/);
    if (commaSplit && commaSplit[1].trim().length >= 2) {
      desc = desc ? commaSplit[2].trim() + ' ' + desc : commaSplit[2].trim();
      name = commaSplit[1].trim();
    }
  }
  // Strip trailing dash-location from name (e.g. "跳水小面-三里屯" → name+desc)
  if (name.length > 6) {
    const dashLoc = name.match(/^(.{2,}?)[-\-](.+)$/);
    if (dashLoc && dashLoc[1].trim().length >= 2 && !/[A-Za-z]/.test(dashLoc[2])) {
      desc = desc ? dashLoc[2].trim() + ' ' + desc : dashLoc[2].trim();
      name = dashLoc[1].trim();
    }
  }
  // For Chinese-only names > 6 chars: split at space boundary between name and feature/location
  // e.g. "33coffee 小院子 东城区隆福寺" or "1959时间里 轻食 院子"
  if (name.length > 6 && !nameEn) {
    // Match: name part (>=2 chars) followed by space + feature words
    const spaceSplit = name.match(/^(.+?)\s+([\u4e00-\u9fff].+)$/);
    if (spaceSplit && spaceSplit[1].trim().length >= 2 && spaceSplit[2].trim().length >= 2) {
      // Only split if the second part looks like feature/location (not part of a name)
      const second = spaceSplit[2].trim();
      if (/[区街路店院子层楼]|轻食|小院|中式|美式|brunch|dirty|舒芙蕾|三里屯|鼓楼|南锣|前门|望京|隆福寺|朝阳|海淀|门头沟|怀柔|三元桥|五道营|亮马|什刹海|王府井|西四|东直门|北新桥/.test(second)) {
        desc = desc ? second + ' ' + desc : second;
        name = spaceSplit[1].trim();
      }
    }
  }
  // For long names with "的" structure: "五只猫娱乐MALL楼顶天台的 Casablanca餐厅" → "Casablanca餐厅"
  // Only when the part before 的 is long/descriptive (>=6 chars) to avoid splitting real names
  if (name.length >= 12) {
    const deMatch = name.match(/^(.{6,})的\s*(.{2,})$/);
    if (deMatch && deMatch[2].trim().length >= 2) {
      desc = desc ? deMatch[1].trim() + ' ' + desc : deMatch[1].trim();
      name = deMatch[2].trim();
    }
  }
  // Truncate very long names at natural break points
  if (name.length > 20) {
    const breakMatch = name.match(/^(.{4,20})[，,。；;、]/);
    if (breakMatch) {
      desc = desc ? name.slice(breakMatch[1].length + 1).trim() + ' ' + desc : name.slice(breakMatch[1].length + 1).trim();
      name = breakMatch[1].trim();
    }
  }
  // Last resort for very long names with Chinese: split at space
  // Skip pure English names (those are likely full proper names like "Toast at The Orchid")
  if (name.length > 16 && /[\u4e00-\u9fff]/.test(name)) {
    const spaceCut = name.match(/^(.{3,15})\s+(.+)$/);
    if (spaceCut && spaceCut[1].trim().length >= 3) {
      desc = desc ? spaceCut[2].trim() + ' ' + desc : spaceCut[2].trim();
      name = spaceCut[1].trim();
    }
  }
  if (!name && nameEn) { name = nameEn; nameEn = ''; }

  return { name, nameEn, desc, tags };
}

function guessEatCategory(line) {
  const l = line.toLowerCase();
  if (/咖啡|coffee|cafe|dirty|拿铁|办公/.test(l)) return 'coffee';
  if (/茶社|茶点|茶室/.test(l)) return 'coffee';
  if (/酒吧|酒馆|微醺|小酌|啤酒|bar|club|wine|精酿|围炉/.test(l)) return 'bar';
  if (/面包|烘焙|甜点|蛋糕|慕斯|bagel|贝果|bakery|司康|碱水|三明治/.test(l)) return 'bakery';
  if (/书局|书屋|书店|展览|美术|艺术|图书|油画/.test(l)) return 'culture';
  if (/live|jazz|音乐|livehouse|脱口秀|相声|演出/.test(l)) return 'leisure';
  if (/市集|冲浪|采摘|温泉|早市/.test(l)) return 'leisure';
  if (/胡同$/.test(line.trim())) return 'culture';
  return 'restaurant';
}

function guessPlayCategory(line) {
  const l = line.toLowerCase();
  if (/美术馆|书局|书店|展览|艺术|图书|纪念馆|帝王庙|寺庙|文化/.test(l)) return 'culture';
  if (/露营|度假|营地|酒店|庄园|野奢/.test(l)) return 'explore';
  if (/live|jazz|音乐|livehouse|脱口秀|相声|演出|爵士|德云/.test(l)) return 'leisure';
  if (/公园/.test(l) && !/慢闪/.test(l)) return 'explore';
  if (/市集|冲浪|采摘|温泉|游船|慢闪/.test(l)) return 'leisure';
  if (/古城|古镇|动物园|古寺|寺$|大观园|水镇|长城/.test(l)) return 'culture';
  if (/山|湖|峰|林|森|岭|沟|涧|溪|岛|湿地|徒步|风景/.test(l)) return 'explore';
  return 'culture';
}

function guessBeijingArea(line) {
  const areaMap = [
    [/鼓楼|南锣|北锣|东棉花/, '鼓楼/南锣'],
    [/前门|桥湾|西兴隆|大栅栏/, '前门/桥湾'],
    [/东四|北新桥|交道口/, '东四/北新桥'],
    [/三里屯|工体|SOHO|团结湖/, '三里屯/工体'],
    [/什刹海|地安门|北海/, '什刹海/地安门'],
    [/西四|白塔寺|阜成门|宫门口/, '西四/白塔寺'],
    [/雍和宫|国子监/, '雍和宫/国子监'],
    [/亮马|蓝港|好运街/, '亮马桥/蓝港'],
    [/朝阳门|建国门|国贸|芳草地|金宝街/, '朝阳门/建国门'],
    [/东直门/, '东直门'],
    [/五道营|安定门/, '五道营/安定门'],
    [/隆福寺/, '隆福寺'],
    [/朝阳公园/, '朝阳公园'],
    [/望京/, '望京'],
    [/门头沟|妙峰|模式口/, '门头沟'],
    [/密云|古北|鹿皮关/, '密云'],
    [/怀柔|神堂峪|百泉|栖乡/, '怀柔'],
    [/平谷|金海湖/, '平谷'],
    [/延庆|野鸭湖|罗锅城|世园/, '延庆'],
    [/海淀|西山|稻香|北坞|鹫峰|阳台山/, '海淀'],
    [/顺义|舞彩/, '顺义'],
    [/丰台|天元/, '丰台'],
    [/牛街|菜市口|法源/, '牛街/菜市口'],
    [/王府井/, '王府井'],
    [/天安门|中山公园/, '天安门'],
    [/西单|宣武/, '西单/宣武门'],
    [/大悦城|朝阳大悦/, '朝阳'],
    [/华熙|五棵松/, '华熙/五棵松'],
    [/合生汇/, '合生汇'],
    [/大钟寺|西直门/, '西直门'],
    [/十里堡/, '十里堡'],
    [/银泰/, '银泰'],
  ];

  for (const [re, area] of areaMap) {
    if (re.test(line)) return area;
  }
  return '其他';
}

// ── Travel note parser ──

function parseTravelNote(text) {
  // Travel note may come as checklist (- [x]/- [ ]) or as plain lines
  // Handle both formats
  const results = [];
  let isOverseas = false;
  const overseasIdx = text.indexOf('国外');
  const skipRe = /^(旅游|🎒|国外|$)/;

  for (const raw of text.split('\n')) {
    const trimmed = raw.trim();
    if (!trimmed || trimmed.length < 3 || skipRe.test(trimmed)) continue;

    // Parse checklist marker if present
    let line = trimmed;
    let visited = false;
    const checkedMatch = line.match(/^- \[x\]\s*(.+)/i);
    const uncheckedMatch = line.match(/^- \[ \]\s*(.+)/);
    if (checkedMatch) { line = checkedMatch[1].trim(); visited = true; }
    else if (uncheckedMatch) { line = uncheckedMatch[1].trim(); }
    else if (line.startsWith('- ')) { line = line.slice(2).trim(); }

    // Skip headers/labels
    if (/^旅游|^🎒|^国外/.test(line)) continue;

    // Determine domestic vs overseas
    const lineIdx = text.indexOf(trimmed);
    if (overseasIdx > -1 && lineIdx > overseasIdx) isOverseas = true;

    const star = line.includes('🌟');
    const clean = line.replace(/🌟/g, '').replace(/✅/g, '').trim();
    if (!clean || clean.length < 2) continue;

    const region = isOverseas ? '海外' : '中国';
    const area = guessTravelArea(clean, isOverseas);
    const { name, nameEn, desc, tags } = parseNameAndDesc(clean);

    results.push({ name, nameEn, cat: 'explore', region, area, desc, star, visited, tags });
  }

  return results;
}

function guessTravelArea(line, isOverseas) {
  if (isOverseas) {
    const countryMap = [
      [/法国|科马/, '法国'], [/德国/, '德国'], [/瑞士/, '瑞士'],
      [/奥地利|维也纳/, '奥地利'], [/匈牙利|布达佩斯/, '匈牙利'],
      [/意大利|多洛米蒂/, '意大利'], [/希腊|罗德/, '希腊'],
      [/塞尔维亚/, '塞尔维亚'], [/格鲁吉亚/, '格鲁吉亚'],
      [/以色列|耶路撒冷/, '以色列'], [/韩国|济州/, '韩国'],
      [/摩洛哥/, '摩洛哥'], [/马来|仙本那|巴厘/, '东南亚'],
      [/加勒比/, '加勒比海'],
    ];
    for (const [re, area] of countryMap) {
      if (re.test(line)) return area;
    }
    return '其他';
  }

  const provinceMap = [
    [/山西|平遥|忻州|大同|云冈|乔家/, '山西'],
    [/山东|济南|九如|台儿庄/, '山东'],
    [/云南|大理|沙溪|罗平|元阳|西双版纳|腾冲/, '云南'],
    [/浙江|莫干|杭州|石舍/, '浙江'],
    [/贵州|肇兴|隆里/, '贵州'],
    [/福建|漳州|福州|厦门|泉州|培田/, '福建'],
    [/广西|桂林|阳朔/, '广西'],
    [/湖南|凤凰|德夯/, '湖南'],
    [/江西|婺源/, '江西'],
    [/四川|恩阳/, '四川'],
    [/新疆/, '新疆'],
    [/西藏/, '西藏'],
    [/河北|阿那亚/, '河北'],
    [/北京|爨底下/, '北京周边'],
  ];
  for (const [re, area] of provinceMap) {
    if (re.test(line)) return area;
  }
  return '其他';
}
